--- #YAML:1.0
name:                Module-Versions-Report
version:             1.05
abstract:            report versions of all modules in memory
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
